import type { TableauWorkbook } from '../parsers/model.js';

export interface IndexEntry {
  workbook: TableauWorkbook;
  subdirName: string;   // e.g. 'accounts-receivable-analysis'
  enriched: boolean;
}

export function generateReportIndex(entries: IndexEntry[], generatedAt: string): string {
  const lines: string[] = [
    `# drexo Analysis Index`,
    ``,
    `> Generated by [drexo](https://github.com/raguvindtharanitharan/drexo) on ${generatedAt}  `,
    `> ${entries.length} workbook${entries.length === 1 ? '' : 's'} analyzed.`,
    ``,
    `| Workbook | Worksheets | Data Sources | Dashboards | Enriched |`,
    `|---------|-----------|-------------|-----------|---------|`,
  ];

  for (const e of entries) {
    const wb = e.workbook;
    const name = `[${wb.metadata.name}](./${e.subdirName}/model.md)`;
    const enriched = e.enriched ? '✓' : '—';
    lines.push(`| ${name} | ${wb.worksheets.length} | ${wb.dataSources.length} | ${wb.dashboards.length} | ${enriched} |`);
  }

  const withSummaries = entries.filter((e) => e.workbook.executiveSummary);
  if (withSummaries.length > 0) {
    lines.push(``, `---`, ``, `## Summaries`, ``);
    for (const e of withSummaries) {
      lines.push(`### ${e.workbook.metadata.name}`);
      lines.push(`> ${e.workbook.executiveSummary}`);
      lines.push(`> [model.md](./${e.subdirName}/model.md) · [visual.md](./${e.subdirName}/visual.md)`);
      lines.push(``);
    }
  }

  return lines.join('\n');
}

export function toSubdirName(filename: string): string {
  return filename
    .replace(/\.twbx?$/, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}
