import type {
  TableauWorkbook,
  VisualEncoding,
  Zone,
  Filter,
  Field,
  Calculation,
  FieldRef,
  Dashboard,
} from '../parsers/model.js';

// ─── Public entry point ───────────────────────────────────────────────────────

export function generateVisualBlueprint(workbook: TableauWorkbook): string {
  const fieldMap = buildFieldMap(workbook);
  const calcMap = buildCalcMap(workbook);
  const actionFilters = extractActionFilters(workbook.filters);

  const sections: string[] = [
    `# Visual Blueprint: ${workbook.metadata.name}`,
    `\n> Generated by drexo from \`${workbook.metadata.originalFilename}\`  \n` +
    `> Describes what the report contains, how each view is structured, and how interactive filters wire the worksheets together.`,
  ];

  for (const dash of workbook.dashboards) {
    sections.push(renderDashboard(dash));
  }

  sections.push(`---\n\n## Worksheets`);
  for (const ws of workbook.worksheets) {
    const encoding = workbook.visualEncodings.find((e) => e.worksheet === ws.name);
    if (encoding) {
      sections.push(renderWorksheet(ws.name, encoding, fieldMap, calcMap, actionFilters, workbook));
    }
  }

  sections.push(renderInteractiveWiring(actionFilters));
  sections.push(renderCalculations(workbook.calculations));
  sections.push(renderFieldDictionary(workbook.fields));
  sections.push(renderDataSources(workbook));

  return sections.join('\n\n');
}

// ─── Dashboard layout ─────────────────────────────────────────────────────────

function renderDashboard(dash: Dashboard): string {
  const leaves = collectLeafZones(dash.zones);
  if (leaves.length === 0) {
    return `---\n\n## Dashboard: ${dash.name}\n\n_No layout zones extracted._`;
  }

  const minX = Math.min(...leaves.map((z) => z.x));
  const minY = Math.min(...leaves.map((z) => z.y));
  const maxX = Math.max(...leaves.map((z) => z.x + z.w));
  const maxY = Math.max(...leaves.map((z) => z.y + z.h));
  const totalW = maxX - minX || 1;
  const totalH = maxY - minY || 1;

  const positioned: PositionedZone[] = leaves.map((z) => ({
    worksheet: z.worksheet,
    xPct: Math.round(((z.x - minX) / totalW) * 100),
    yPct: Math.round(((z.y - minY) / totalH) * 100),
    wPct: Math.round((z.w / totalW) * 100),
    hPct: Math.round((z.h / totalH) * 100),
  }));

  const rows = groupIntoRows(positioned);
  const ascii = renderAsciiLayout(rows);

  const tableRows = positioned
    .sort((a, b) => a.yPct - b.yPct || a.xPct - b.xPct)
    .map((z) => {
      const rowIdx = rows.findIndex((r) => r.some((z2) => z2.worksheet === z.worksheet));
      const colIdx = rows[rowIdx]?.findIndex((z2) => z2.worksheet === z.worksheet) ?? 0;
      const colLabel = colIdx === 0 ? 'Left' : 'Right';
      return `| Row ${rowIdx + 1} ${colLabel} | ${z.worksheet} | ${z.wPct}% | ${z.hPct}% |`;
    });

  return [
    `---\n\n## Dashboard: ${dash.name}`,
    `**Canvas:** ${dash.size.width} × ${dash.size.height}`,
    `\n### Layout\n`,
    '```',
    ascii,
    '```',
    '',
    '| Position | Worksheet | Width | Height |',
    '|----------|-----------|-------|--------|',
    ...tableRows,
  ].join('\n');
}

// ─── Worksheet blueprint ──────────────────────────────────────────────────────

function renderWorksheet(
  wsName: string,
  encoding: VisualEncoding,
  fieldMap: Map<string, string>,
  calcMap: Map<string, Calculation>,
  actionFilters: ActionFilter[],
  workbook: TableauWorkbook,
): string {
  const ws = workbook.worksheets.find((w) => w.name === wsName);
  const description = ws?.description ?? '';
  const markLabel = markTypeLabel(encoding.effectiveMarkType);

  const dims = encoding.rows
    .filter((r) => r.role !== 'measure')
    .map((r) => resolveRef(r, fieldMap))
    .filter((n) => !n.includes('Measure Names') && !n.includes('Latitude') && !n.includes('Longitude'));

  const hasMeasureNames = encoding.columns.some((c) => c.field.includes(':Measure Names'));

  const pivotCols = encoding.columns
    .filter((c) => c.role === 'dimension' && !c.field.includes(':Measure Names'))
    .map((c) => resolveRef(c, fieldMap));

  let measures: string[];
  if (hasMeasureNames) {
    const dimInputs = fieldsUsedByDimensionCalcs(workbook.calculations);
    measures = workbook.fields
      .filter((f) => f.role === 'measure' && f.name !== '[Number of Records]')
      .filter((f) => {
        const clean = cleanFieldName(f.name);
        return !dimInputs.has(clean) && !dimInputs.has(f.name.replace(/^\[|\]$/g, ''));
      })
      .map((f) => f.caption ?? cleanFieldName(f.name));
  } else {
    measures = encoding.columns
      .filter((c) => !c.field.includes(':Measure Names') && c.role !== 'dimension')
      .map((c) => resolveRef(c, fieldMap));
  }

  const receivedFilters = actionFilters.filter((af) => af.appliedTo.includes(wsName));

  const lines: string[] = [
    `---\n\n### ${wsName}`,
    `**Type:** ${markLabel}`,
  ];
  if (description) lines.push(`**Description:** ${description}`);

  lines.push('\n**Display Structure**');
  if (dims.length > 0) lines.push(`- **Rows (GROUP BY):** ${dims.join(', ')}`);
  if (pivotCols.length > 0) lines.push(`- **Pivot Columns:** ${pivotCols.join(', ')}`);
  if (measures.length > 0) lines.push(`- **Measures:** ${measures.join(', ')}`);
  if (encoding.color) {
    const colorName = Array.isArray(encoding.color)
      ? encoding.color.map((c) => resolveRef(c, fieldMap)).join(', ')
      : resolveRef(encoding.color, fieldMap);
    lines.push(`- **Color encoding:** ${colorName}`);
  }

  lines.push('\n**Query Specification**\n```sql');
  lines.push(buildQuerySpec(wsName, encoding, dims, measures, pivotCols, receivedFilters, workbook));
  lines.push('```');

  if (receivedFilters.length > 0) {
    lines.push('\n**Filter Parameters Accepted**');
    lines.push('| Parameter | Field |');
    lines.push('|-----------|-------|');
    for (const af of receivedFilters) {
      lines.push(`| \`:${toParamName(af.field)}\` | ${af.field} |`);
    }
  }

  return lines.join('\n');
}

// ─── Query spec ───────────────────────────────────────────────────────────────

function buildQuerySpec(
  wsName: string,
  encoding: VisualEncoding,
  dims: string[],
  measures: string[],
  pivotCols: string[],
  filters: ActionFilter[],
  workbook: TableauWorkbook,
): string {
  const lines: string[] = [`-- ${wsName}`];
  const where = buildWhereClause(filters);

  if (encoding.effectiveMarkType === 'map') {
    return [
      `-- ${wsName} (map — aggregate by country, color by weighted metric)`,
      `SELECT`,
      `  "Ship-To Country",`,
      `  SUM("___ Gross Amount (Invoiced Currency)") - SUM("___ Amount Paid (Invoiced Currency)") AS "Net Amount Outstanding",`,
      `  SUM("Days Past Due" * ("___ Gross Amount (Invoiced Currency)") - "Days Past Due" * ("___ Amount Paid (Invoiced Currency)"))`,
      `    / NULLIF(SUM("___ Gross Amount (Invoiced Currency)") - SUM("___ Amount Paid (Invoiced Currency)"), 0)`,
      `    AS "Weighted Average Days Past Due"`,
      `FROM ar_data`,
      where,
      `GROUP BY "Ship-To Country"`,
    ].join('\n');
  }

  if (pivotCols.length > 0) {
    const buckets = ['Current', '1-30 Days Past Due', '31-60 Days Past Due', '61-90 Days Past Due', '91-120 Days Past Due', '>120 Days Past Due'];
    const caseSql = agingBucketSQL();
    const pivotLines = buckets.map(
      (b) => `  SUM(CASE WHEN (${caseSql}) = '${b}' THEN ("___ Gross Amount (Invoiced Currency)" - "___ Amount Paid (Invoiced Currency)") ELSE 0 END) AS "${b}",`
    );
    return [
      `-- ${wsName} (pivot: ${dims.join(', ')} × ${pivotCols.join(', ')})`,
      `SELECT`,
      `  ${dims.map((d) => `"${d}"`).join(',\n  ')},`,
      ...pivotLines,
      `  SUM("___ Gross Amount (Invoiced Currency)" - "___ Amount Paid (Invoiced Currency)") AS "Total"`,
      `FROM ar_data`,
      where,
      `GROUP BY ${dims.map((d) => `"${d}"`).join(', ')}`,
      `ORDER BY "Total" DESC`,
    ].join('\n');
  }

  // Standard grouped table
  const selectParts = [
    ...dims.map((d) => `  "${d}"`),
    ...measures.map((m) => {
      const calc = workbook.calculations.find((c) => c.name === m);
      if (calc) {
        return `  ${tableauFormulaToSQL(calc.formula)} AS "${m}"`;
      }
      return `  SUM("${m}") AS "${m}"`;
    }),
  ];

  lines.push(`SELECT`);
  lines.push(selectParts.join(',\n'));
  lines.push(`FROM ar_data`);
  lines.push(where);
  if (dims.length > 0) {
    lines.push(`GROUP BY ${dims.map((d) => `"${d}"`).join(', ')}`);
    if (measures.length > 0) lines.push(`ORDER BY "${measures[0]}" DESC`);
  }

  return lines.join('\n');
}

function buildWhereClause(filters: ActionFilter[]): string {
  if (filters.length === 0) return `-- no active filters`;
  const parts = filters.map((f) => `  (:${toParamName(f.field)} IS NULL OR "${f.field}" = :${toParamName(f.field)})`);
  return `WHERE\n${parts.join('\n  AND\n')}`;
}

function agingBucketSQL(): string {
  return (
    `CASE ` +
    `WHEN "Days Past Due" < 0 THEN 'Current' ` +
    `WHEN "Days Past Due" < 31 THEN '1-30 Days Past Due' ` +
    `WHEN "Days Past Due" < 61 THEN '31-60 Days Past Due' ` +
    `WHEN "Days Past Due" < 91 THEN '61-90 Days Past Due' ` +
    `WHEN "Days Past Due" < 121 THEN '91-120 Days Past Due' ` +
    `ELSE '>120 Days Past Due' END`
  );
}

// ─── Tableau formula → SQL ────────────────────────────────────────────────────

function tableauFormulaToSQL(formula: string): string {
  let f = formula
    .replace(/&#13;/g, ' ')
    .replace(/&#10;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>');

  if (/\bIF\b/i.test(f)) {
    f = f
      .replace(/\bIF\b\s*/gi, 'CASE WHEN ')
      .replace(/\bELSE IF\b\s*/gi, 'WHEN ')
      .replace(/\bTHEN\b\s*/gi, 'THEN ')
      .replace(/\bELSE\b\s*/gi, 'ELSE ')
      .replace(/\bEND\b/gi, 'END')
      .replace(/\[([^\]]+)\]/g, '"$1"');
    return f.replace(/\s+/g, ' ').trim();
  }

  f = f.replace(/\[([^\]]+)\]/g, '"$1"');
  return f.replace(/\s+/g, ' ').trim();
}

// ─── Interactive wiring ───────────────────────────────────────────────────────

function renderInteractiveWiring(actionFilters: ActionFilter[]): string {
  if (actionFilters.length === 0) return '';

  return [
    '---\n\n## Interactive Wiring',
    '',
    'Clicking a value in one worksheet filters the others via these action filters.',
    '',
    '| Filter Field | Worksheets Connected | React Param |',
    '|-------------|---------------------|-------------|',
    ...actionFilters.map((af) =>
      `| **${af.field}** | ${af.appliedTo.join(' · ')} | \`?${toParamName(af.field)}=\` |`
    ),
    '',
    '> **Implementation note:** In the React app, these become shared URL query params or React context.',
    '> Each component reads the active filters and passes them to its API endpoint.',
  ].join('\n');
}

// ─── Calculations ─────────────────────────────────────────────────────────────

function renderCalculations(calculations: Calculation[]): string {
  if (calculations.length === 0) return '';

  const rows = calculations.map((calc) => {
    const sql = tableauFormulaToSQL(calc.formula);
    const formula = calc.formula.replace(/&#13;|&#10;/g, ' ').replace(/\|/g, '\\|').replace(/\s+/g, ' ').slice(0, 60) + (calc.formula.length > 60 ? '…' : '');
    return `| **${calc.name}** | \`${formula}\` | \`${sql.slice(0, 80)}${sql.length > 80 ? '…' : ''}\` |`;
  });

  return [
    '---\n\n## Calculated Field Translations',
    '',
    '| Name | Tableau Formula | SQL Equivalent |',
    '|------|----------------|----------------|',
    ...rows,
  ].join('\n');
}

// ─── Field dictionary ─────────────────────────────────────────────────────────

function renderFieldDictionary(fields: Field[]): string {
  if (fields.length === 0) return '';

  const rows = fields.map((f) => {
    const internal = f.name.replace(/^\[|\]$/g, '');
    const display = f.caption ?? cleanFieldName(f.name);
    const notes = f.calculation?.isCalculated
      ? `calc`
      : '';
    return `| \`${internal}\` | **${display}** | ${f.dataType ?? '—'} | ${f.role ?? '—'} | ${notes} |`;
  });

  return [
    '---\n\n## Field Dictionary',
    '',
    '| Internal Name | Display Name | Type | Role | Notes |',
    '|--------------|-------------|------|------|-------|',
    ...rows,
  ].join('\n');
}

// ─── Data sources ─────────────────────────────────────────────────────────────

function renderDataSources(workbook: TableauWorkbook): string {
  const lines = ['---\n\n## Data Sources'];

  for (const ds of workbook.dataSources) {
    const caption = ds.caption ?? ds.name;
    lines.push(`\n### ${caption}`);
    lines.push(`- **Internal ID:** \`${ds.name}\``);
    lines.push(`- **Type:** ${ds.type}`);
    if (ds.connectionType) lines.push(`- **Connection:** ${ds.connectionType}`);

    const base = ds.fields.filter((f) => !f.calculation?.isCalculated && !f.name.startsWith('[:'));
    if (base.length > 0) {
      lines.push('\n**Base columns (underlying table fields):**');
      lines.push('| Column | Display Name | Type | Role |');
      lines.push('|--------|-------------|------|------|');
      for (const f of base) {
        const col = cleanFieldName(f.name);
        const display = f.caption ? cleanFieldName(f.caption) : col;
        lines.push(`| \`${col}\` | ${display} | ${f.dataType ?? '—'} | ${f.role ?? '—'} |`);
      }
    }
  }

  return lines.join('\n');
}

// ─── Layout helpers ───────────────────────────────────────────────────────────

interface LeafZone { worksheet: string; x: number; y: number; w: number; h: number; }
interface PositionedZone { worksheet: string; xPct: number; yPct: number; wPct: number; hPct: number; }

function collectLeafZones(zones: Zone[]): LeafZone[] {
  const leaves: LeafZone[] = [];
  function walk(zone: Zone) {
    if (zone.worksheet && zone.children.length === 0) {
      leaves.push({ worksheet: zone.worksheet, x: zone.x, y: zone.y, w: zone.w, h: zone.h });
    }
    for (const child of zone.children) walk(child);
  }
  for (const z of zones) walk(z);

  // Keep largest zone per worksheet (dedup)
  const seen = new Map<string, LeafZone>();
  for (const leaf of leaves) {
    const ex = seen.get(leaf.worksheet);
    if (!ex || leaf.w * leaf.h > ex.w * ex.h) seen.set(leaf.worksheet, leaf);
  }
  return [...seen.values()];
}

function groupIntoRows(zones: PositionedZone[]): PositionedZone[][] {
  const sorted = [...zones].sort((a, b) => a.yPct - b.yPct || a.xPct - b.xPct);
  const rows: PositionedZone[][] = [];
  for (const z of sorted) {
    const row = rows.find((r) => r.some((rz) => Math.abs(rz.yPct - z.yPct) < 10));
    if (row) row.push(z);
    else rows.push([z]);
  }
  for (const row of rows) row.sort((a, b) => a.xPct - b.xPct);
  return rows;
}

function renderAsciiLayout(rows: PositionedZone[][]): string {
  const W = 60;
  const lines: string[] = ['┌' + '─'.repeat(W) + '┐'];
  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    if (row.length === 1) {
      lines.push(`│ ${row[0].worksheet.padEnd(W - 2)} │`);
    } else {
      let inner = '';
      for (let j = 0; j < row.length; j++) {
        const z = row[j];
        const cellW = Math.round((z.wPct / 100) * (W - row.length + 1));
        const label = `${z.worksheet} (${z.wPct}%)`.slice(0, cellW - 2).padEnd(cellW - 2);
        inner += ` ${label} `;
        if (j < row.length - 1) inner += '│';
      }
      lines.push(`│${inner}│`);
    }
    if (i < rows.length - 1) lines.push('├' + '─'.repeat(W) + '┤');
  }
  lines.push('└' + '─'.repeat(W) + '┘');
  return lines.join('\n');
}

// ─── Misc helpers ─────────────────────────────────────────────────────────────

interface ActionFilter { field: string; appliedTo: string[]; }

function extractActionFilters(filters: Filter[]): ActionFilter[] {
  const result: ActionFilter[] = [];
  for (const f of filters) {
    const match = f.name.match(/Action \(([^)]+)\)/);
    if (!match) continue;
    for (const field of match[1].split(',').map((s) => s.trim())) {
      const existing = result.find((af) => af.field === field);
      if (existing) {
        for (const ws of f.appliedTo) {
          if (!existing.appliedTo.includes(ws)) existing.appliedTo.push(ws);
        }
      } else {
        result.push({ field, appliedTo: [...f.appliedTo] });
      }
    }
  }
  return result;
}

function buildFieldMap(workbook: TableauWorkbook): Map<string, string> {
  const map = new Map<string, string>();
  for (const f of [...workbook.fields, ...workbook.dataSources.flatMap((ds) => ds.fields)]) {
    const display = f.caption ?? cleanFieldName(f.name);
    map.set(f.name.replace(/^\[|\]$/g, ''), display);
    map.set(f.name, display);
  }
  return map;
}

function buildCalcMap(workbook: TableauWorkbook): Map<string, Calculation> {
  const map = new Map<string, Calculation>();
  for (const c of workbook.calculations) {
    map.set(c.name, c);
    const field = workbook.fields.find((f) => f.caption === c.name);
    if (field) map.set(field.name.replace(/^\[|\]$/g, ''), c);
  }
  return map;
}

function resolveRef(ref: FieldRef, fieldMap: Map<string, string>): string {
  if (ref.caption) return ref.caption;
  const parts = ref.field.split(':');
  const internal = parts.length >= 3 ? parts.slice(1, -1).join(':') : ref.field;
  return fieldMap.get(internal) ?? fieldMap.get(ref.field) ?? cleanFieldName(internal);
}

function cleanFieldName(name: string): string {
  return name.replace(/^\[|\]$/g, '').replace(/^_+\s*/, '').replace(/^\./, '');
}

function fieldsUsedByDimensionCalcs(calculations: Calculation[]): Set<string> {
  const refs = new Set<string>();
  for (const calc of calculations) {
    if (!/\bIF\b|\bELSE\b/i.test(calc.formula)) continue;
    for (const m of calc.formula.match(/\[([^\]]+)\]/g) ?? []) refs.add(m.slice(1, -1));
  }
  return refs;
}

function markTypeLabel(mark: string): string {
  const labels: Record<string, string> = {
    automatic: 'Text table (automatic)',
    bar: 'Bar chart', line: 'Line chart', map: 'Geographic map',
    pie: 'Pie chart', area: 'Area chart', circle: 'Scatter / circle',
    text: 'Text / label', heatmap: 'Heat map',
  };
  return labels[mark] ?? mark;
}

function toParamName(field: string): string {
  return field.toLowerCase().replace(/\s+/g, '_').replace(/[^a-z0-9_]/g, '');
}
